// RUN-238: the committed load harness for the indexer's event-loop/memory profile on a large
// monorepo. Separate from `npm run test`/`npm run check` on purpose (this is a load test, not a
// correctness test — it takes tens of seconds and its numbers are host-dependent) — run it
// directly: `npx tsx bench/index-load.mts [--files N] [--yield-files N] [--yield-records N] [--keep]
// [--skip-determinism]`.
//
// This is the committed descendant of the anchor probe (`load238b.mts`, taken before this task's
// spec was written) that first measured the defect: a single continuous 6.3s event-loop block on
// an 8000-file/335920-record synthetic tree, because `await adapter.parse(...)` in the candidate
// loop is a microtask continuation that never lets a timer or the poll phase run, and the
// synchronous tail (`sortRecords`/`computeContentHash`/`encodeBatches`) ran inside the same
// unbroken block. See INDEX-OPERATIONS.md's "Load and memory budgets (RUN-238)" section for the
// numbers this harness produced on this repo's own host, and this repo's `src/index-batch.ts` /
// `src/indexer.ts` for the fix (cooperative `setImmediate` checkpoints, never a microtask yield —
// see those files' own module docs for why a microtask yield would look like a fix and change
// nothing).
//
// **The lag probe must OUTLIVE the work it measures** (the first-probe artifact this harness's own
// ancestor documented): a `setInterval` cleared the instant the awaited work resolves never fires
// the tick that would have REPORTED a block spanning right up to that resolution — so a genuinely
// blocked loop reads as a perfectly healthy one. This harness lets its lag interval run past every
// phase and only clears it after an explicit trailing pause.
//
// **Determinism is proven on the real generated tree, not only in a fixture-sized unit test**
// (RUN-238 acceptance) — `runDeterminismCheck` below runs the full indexer twice over the same
// synthetic tree and compares canonical output byte-for-byte via `compareGenerations`, the same
// function `index-repo.ts --check-determinism` uses for a real checkout.

import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
import { computeContentHash, encodeBatches, sortRecords } from '../src/index-batch';
import { compareGenerations } from '../src/index-debug';
import { INDEX_LANGUAGES } from '../src/index-policy';
import type { ResolvedIndexConfig } from '../src/index-policy';
import { buildIndexAdapterRegistry } from '../src/index-registry';
import { scanIndexSource } from '../src/index-scan';
import { FilesystemIndexSource } from '../src/index-source';
import { runIndexer } from '../src/indexer';

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

function argNum(flag: string, fallback: number): number {
  const i = process.argv.indexOf(flag);
  if (i === -1) return fallback;
  const v = Number(process.argv[i + 1]);
  return Number.isFinite(v) && v > 0 ? v : fallback;
}
function argFlag(flag: string): boolean {
  return process.argv.includes(flag);
}

const FILE_COUNT = argNum('--files', 8000);
const FUNCS_PER_FILE = 12; // + 1 combinator function + 1 interface + 1 relative import, per file.
const FILES_PER_DIR = 100;
const YIELD_FILES = argNum('--yield-files', 0) || undefined; // 0/absent => production default.
const YIELD_RECORDS = argNum('--yield-records', 0) || undefined;
const KEEP_TREE = argFlag('--keep');
// See `printInstrumentedPass`'s own doc: the determinism check holds TWO more full generations
// live at once, on top of whatever GC has not yet reclaimed from the pass just printed. Cheap at
// the default 8000-file size (this is RUN-238's own required proof, so it stays ON by default);
// opt out for a much larger `--files` run where that cost genuinely dominates.
const SKIP_DETERMINISM = argFlag('--skip-determinism');

// ---------------------------------------------------------------------------
// Synthetic tree generator — the same shape the RUN-238 anchor measurement used (12 numbered
// helper functions + 1 combinator + 1 interface + 1 relative import per file), so numbers taken
// with this harness are comparable to the ones already recorded in INDEX-OPERATIONS.md. Committed
// here (rather than a one-off scratchpad script) per this task's own acceptance: the generator
// must be reproducible from source control, not regenerated by hand each time someone asks
// "how does this behave on a large repo."
// ---------------------------------------------------------------------------

function fileContent(index: number): string {
  const lines: string[] = [];
  if (index > 0) lines.push(`import { fn${index - 1} } from "./f${index - 1}";`);
  const prevShape = index > 0 ? `Shape${index - 1}` : 'null';
  lines.push(`export interface Shape${index} { a: string; b: number; c: ${prevShape} | null }`);
  for (let i = 0; i < FUNCS_PER_FILE; i++) {
    lines.push(`export function fn${index}_${i}(x: number): number {`);
    lines.push('  // some comment line to add bytes xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
    lines.push(`  return x * ${i} + ${index};`);
    lines.push('}');
  }
  const calls = Array.from({ length: FUNCS_PER_FILE }, (_, i) => `fn${index}_${i}(1)`).join(' + ');
  lines.push(`export function fn${index}(){ return ${calls}; }`);
  return `${lines.join('\n')}\n`;
}

async function generateTree(root: string, fileCount: number): Promise<{ bytes: number }> {
  let bytes = 0;
  const dirCount = Math.max(1, Math.ceil(fileCount / FILES_PER_DIR));
  for (let d = 0; d < dirCount; d++) {
    await mkdir(path.join(root, 'src', `m${d}`), { recursive: true });
  }
  for (let i = 0; i < fileCount; i++) {
    const dir = Math.floor(i / FILES_PER_DIR);
    const content = fileContent(i);
    bytes += Buffer.byteLength(content, 'utf8');
    await writeFile(path.join(root, 'src', `m${dir}`, `f${i}.ts`), content);
  }
  return { bytes };
}

// ---------------------------------------------------------------------------
// Instrumentation — event-loop lag (must outlive the work), peak RSS/heapUsed.
// ---------------------------------------------------------------------------

interface LagSample {
  at: number;
  lag: number;
}

function startLagProbe(intervalMs: number): { lags: LagSample[]; stop: () => void } {
  const lags: LagSample[] = [];
  const start = Date.now();
  let last = Date.now();
  const beat = setInterval(() => {
    const now = Date.now();
    lags.push({ at: now - start, lag: now - last - intervalMs });
    last = now;
  }, intervalMs);
  return { lags, stop: () => clearInterval(beat) };
}

function startMemProbe(intervalMs: number): {
  peak: () => { rss: number; heapUsed: number };
  stop: () => void;
} {
  let peakRss = 0;
  let peakHeap = 0;
  const timer = setInterval(() => {
    const m = process.memoryUsage();
    peakRss = Math.max(peakRss, m.rss);
    peakHeap = Math.max(peakHeap, m.heapUsed);
  }, intervalMs);
  return { peak: () => ({ rss: peakRss, heapUsed: peakHeap }), stop: () => clearInterval(timer) };
}

function pct(sortedLags: number[], p: number): number {
  if (sortedLags.length === 0) return 0;
  return sortedLags[Math.min(sortedLags.length - 1, Math.floor((sortedLags.length * p) / 100))] ?? 0;
}

const mb = (n: number): string => `${(n / 1024 / 1024).toFixed(1)} MB`;

// ---------------------------------------------------------------------------
// One indexing pass, instrumented.
// ---------------------------------------------------------------------------

function config(): ResolvedIndexConfig {
  return {
    languages: [...INDEX_LANGUAGES],
    contentMode: 'full',
    maxFiles: 20_000,
    maxFileBytes: 1_000_000,
    maxTotalBytes: 500_000_000,
    readDeadlineMs: 600_000,
    pollIntervalMinutes: 60,
    include: [],
    exclude: [],
  };
}

async function runInstrumentedPass(root: string) {
  const lag = startLagProbe(50);
  const mem = startMemProbe(50);
  const marks: Array<[string, number]> = [];
  const mark = (label: string, ms: number) => marks.push([label, ms]);

  const cfg = config();
  const { registry } = buildIndexAdapterRegistry(cfg);

  let t = Date.now();
  const scan = await scanIndexSource(new FilesystemIndexSource(root), cfg);
  mark('scan', Date.now() - t);
  const scannedBytes = scan.candidates.reduce(
    (n, c) => n + (c.contentMode === 'full' ? c.content.length : 0),
    0,
  );

  t = Date.now();
  const result = await runIndexer(
    new FilesystemIndexSource(root),
    cfg,
    {
      projectId: 'prj_probe',
      projectKey: 'probe',
      repositoryKey: 'probe-repo',
      branch: 'main',
      baseId: 'deadbeef',
    },
    { adapters: registry, yieldEveryFiles: YIELD_FILES, yieldEveryRecords: YIELD_RECORDS },
  );
  mark('runIndexer (scan+parse+sort+hash+encode, yielding)', Date.now() - t);

  // Phase breakdown for the three tail stages, timed in ISOLATION on the already-finished records
  // — informational (the real pass above is what the lag/memory probes actually observed), same
  // structure as the anchor probe this harness descends from.
  const unsorted = [...result.records];
  t = Date.now();
  const sorted = sortRecords(unsorted);
  mark('  sortRecords (sync, not chunked — see index-batch.ts)', Date.now() - t);
  t = Date.now();
  await computeContentHash(sorted, { yieldEveryRecords: YIELD_RECORDS });
  mark('  computeContentHash (chunked)', Date.now() - t);
  t = Date.now();
  const batches = await encodeBatches(result.manifest.generationId, sorted, {
    yieldEveryRecords: YIELD_RECORDS,
  });
  mark('  encodeBatches / gzipSync (chunked)', Date.now() - t);

  const biggest = batches.reduce((a, b) => (b.compressed.byteLength > a.compressed.byteLength ? b : a));
  t = Date.now();
  gzipSync(Buffer.from('x'.repeat(biggest.compressed.byteLength)));
  mark('  one gzipSync of the largest batch size', Date.now() - t);

  // Let the loop breathe so the tick that would report a trailing block actually fires — the
  // "first-probe artifact" lesson this harness's own module doc names.
  await new Promise((r) => setTimeout(r, 400));
  lag.stop();
  mem.stop();

  const sortedLags = lag.lags.map((l) => l.lag).sort((a, b) => a - b);
  const peak = mem.peak();

  return { result, scan, scannedBytes, marks, lags: lag.lags, sortedLags, peak };
}

async function runDeterminismCheck(root: string) {
  const cfg = config();
  const { registry: r1 } = buildIndexAdapterRegistry(cfg);
  const { registry: r2 } = buildIndexAdapterRegistry(cfg);
  const target = {
    projectId: 'prj_probe',
    projectKey: 'probe',
    repositoryKey: 'probe-repo',
    branch: 'main',
    baseId: 'deadbeef',
  };
  const first = await runIndexer(new FilesystemIndexSource(root), cfg, target, { adapters: r1 });
  const second = await runIndexer(new FilesystemIndexSource(root), cfg, target, { adapters: r2 });
  return compareGenerations(first, second);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

/**
 * Runs the instrumented pass and prints everything it measured, returning only the one small
 * string a later section still needs (`contentHash`) — deliberately NOT the `IndexerResult` or the
 * `IndexerResult` itself: at maxFiles-adjacent scale that object graph is hundreds of MB (records,
 * batches, lag samples), and `main()` still has the determinism check ahead of it, which allocates
 * TWO MORE full generations. Keeping this pass's own result reachable through that would triple
 * peak live heap for no reason — measured to matter: an earlier draft of this harness that DID keep
 * it reachable spent 10+ minutes thrashing in GC on a 20000-file tree instead of the ~20s a single
 * pass takes, CPU-bound and never crashing, which is its own real finding (see
 * INDEX-OPERATIONS.md's own note on why the determinism check is scoped the way it is below).
 */
async function printInstrumentedPass(root: string): Promise<string> {
  const pass = await runInstrumentedPass(root);
  const { result, scan, scannedBytes, marks, peak, sortedLags } = pass;

  console.log(`\nroot: ${root}`);
  console.log(`files scanned:      ${scan.candidates.length}   content bytes: ${mb(scannedBytes)}`);
  console.log(`records:            ${result.records.length}`);
  console.log(
    `batches:            ${result.batches.length}   gzipped total: ${mb(result.batches.reduce((n, b) => n + b.compressed.byteLength, 0))}`,
  );
  console.log(`peak rss:           ${mb(peak.rss)}    peak heapUsed: ${mb(peak.heapUsed)}`);
  console.log('\nphase timings:');
  for (const [label, ms] of marks) console.log(`  ${label.padEnd(56)} ${ms} ms`);
  console.log(
    `\nevent-loop lag on a 50ms interval (${pass.lags.length} ticks over ${pass.lags.at(-1)?.at ?? 0} ms):`,
  );
  console.log(
    `  p50 ${pct(sortedLags, 50)}   p90 ${pct(sortedLags, 90)}   p99 ${pct(sortedLags, 99)}   MAX ${sortedLags.at(-1) ?? 0} ms`,
  );
  console.log('  worst 6 stalls (at ms into run -> late by ms):');
  for (const l of [...pass.lags].sort((a, b) => b.lag - a.lag).slice(0, 6))
    console.log(`    ${l.at} -> ${l.lag}`);
  console.log(
    `  ticks late by >250ms: ${sortedLags.filter((l) => l > 250).length}   >1s: ${sortedLags.filter((l) => l > 1000).length}   >5s: ${sortedLags.filter((l) => l > 5000).length}`,
  );
  return result.manifest.contentHash;
}

async function main() {
  const root = await mkdtemp(path.join(os.tmpdir(), 'noriq-index-load-'));
  try {
    console.log(`generating synthetic tree: ${FILE_COUNT} files under ${root}`);
    const gen = await generateTree(root, FILE_COUNT);
    console.log(`generated: ${mb(gen.bytes)} of source text`);
    if (YIELD_FILES) console.log(`override: yieldEveryFiles=${YIELD_FILES}`);
    if (YIELD_RECORDS) console.log(`override: yieldEveryRecords=${YIELD_RECORDS}`);

    const contentHash = await printInstrumentedPass(root);

    if (SKIP_DETERMINISM) {
      console.log('\n--skip-determinism passed: not re-indexing twice more to compare.');
      console.log(`  contentHash: ${contentHash}`);
      return;
    }
    console.log('\ndeterminism check (indexing the same tree twice, comparing canonical output):');
    const det = await runDeterminismCheck(root);
    console.log(`  ok: ${det.ok}${det.ok ? '' : `   mismatches: ${det.mismatches.join('; ')}`}`);
    console.log(`  contentHash: ${contentHash}`);

    if (!det.ok) process.exitCode = 1;
  } finally {
    if (KEEP_TREE) {
      console.log(`\n--keep passed: leaving the generated tree at ${root}`);
    } else {
      await rm(root, { recursive: true, force: true });
    }
  }
}

await main();
