import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { hashTree } from "./vendor-provenance.mjs";

const sourceRoot = resolve(process.argv[2] ?? "../noriq");
const source = resolve(sourceRoot, "packages/shared/src");
const destinationRoot = resolve("vendor/noriq-shared");
const destination = resolve(destinationRoot, "src");
if (!existsSync(source))
  throw new Error(`Noriq shared source not found at ${source}`);
const sourceCommit = execFileSync("git", ["rev-parse", "HEAD"], {
  cwd: sourceRoot,
  encoding: "utf8",
}).trim();
const sourceDirty =
  execFileSync("git", ["status", "--porcelain", "--", "packages/shared/src"], {
    cwd: sourceRoot,
    encoding: "utf8",
  }).trim().length > 0;
if (sourceDirty)
  throw new Error("refusing to vendor an uncommitted packages/shared/src tree");
await rm(destination, { recursive: true, force: true });
await mkdir(destinationRoot, { recursive: true });
await cp(source, destination, { recursive: true });
await writeFile(
  resolve(destinationRoot, "package.json"),
  `${JSON.stringify({ name: "@noriq-dev/shared", version: "0.0.0-vendored", type: "module", exports: { ".": "./src/index.ts" }, dependencies: { zod: "^4.0.0" } }, null, 2)}\n`,
);
await writeFile(
  resolve(destinationRoot, "README.md"),
  "# Vendored Noriq shared contract\n\nGenerated by `npm run vendor:shared`; never edit this directory by hand.\n",
);
await writeFile(
  resolve(destinationRoot, "PROVENANCE.json"),
  `${JSON.stringify({ sourceCommit, sourceDirty, vendoredAt: new Date().toISOString(), files: await hashTree(destination) }, null, 2)}\n`,
);
process.stdout.write(`Vendored @noriq-dev/shared from ${sourceCommit}\n`);
